{{- if .Values.sockShop.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    litmuschaos.io/chaos: "true"
  labels:
    app: sock-shop
    name: rabbitmq
  name: rabbitmq
  namespace: {{ include "sock-shop-litmus.sockShopNamespace" . }}
spec:
  replicas: {{ .Values.sockShop.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: sock-shop
      name: rabbitmq
  template:
    metadata:
      labels:
        app: sock-shop
        name: rabbitmq
    spec:
      containers:
      - image: {{ .Values.sockShop.rabbitmq.image }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        name: rabbitmq
        ports:
        - containerPort: 5672
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            - DAC_OVERRIDE
            drop:
            - all
          readOnlyRootFilesystem: true
{{- end }}
