{{- if .Values.sockShop.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    litmuschaos.io/chaos: "true"
  labels:
    app: sock-shop
    name: carts-db
  name: carts-db
  namespace: {{ include "sock-shop-litmus.sockShopNamespace" . }}
spec:
  replicas: {{ .Values.sockShop.cartsDb.replicas }}
  selector:
    matchLabels:
      app: sock-shop
      name: carts-db
  template:
    metadata:
      labels:
        app: sock-shop
        name: carts-db
    spec:
      containers:
      - image: {{ .Values.sockShop.cartsDb.image }}
        imagePullPolicy: Always
        name: carts-db
        ports:
        - containerPort: 27017
          name: mongo
          protocol: TCP
        resources:
          limits:
            ephemeral-storage: {{ .Values.sockShop.cartsDb.resources.limits.ephemeralStorage }}
          requests:
            ephemeral-storage: {{ .Values.sockShop.cartsDb.resources.requests.ephemeralStorage }}
        securityContext:
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            drop:
            - all
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
      - emptyDir:
          medium: Memory
        name: tmp-volume
{{- end }}
