{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ include "sock-shop-litmus.monitoringNamespace" . }}
spec:
  ports:
  - nodePort: {{ .Values.monitoring.grafana.service.nodePort }}
    port: {{ .Values.monitoring.grafana.service.port }}
    protocol: TCP
    targetPort: {{ .Values.monitoring.grafana.service.port }}
  selector:
    app: grafana
  sessionAffinity: None
  type: {{ .Values.monitoring.grafana.service.type }}
{{- end }}
